[package]
name = "advent"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_file = {path = "../read_file"}
task_3 = {path = "../task_3"}
task_4 = {path = "../task_4"}