[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_file = {path = "../read_file"}
task_3 = {path = "../task_3"}
task_4 = {path = "../task_4"}